name: FIOO BACK END RENDER PUSH

on:
  push:
    branches: [ "PROD" ]
  pull_request:
    branches: [ "PROD" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Render Deploy Action
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{secrets.SERVICE_ID}}
        api-key: ${{secrets.API_KEY}}
